### ISSUE TITLE
Modify: Add information on how to Switch Outlook/Hotmail accounts from `Normal password` to `OAuth2` in the KB article on Microsoft OAuth

### ISSUE THREAD

**Issue by monica-thunderbird** [thunderbird/knowledgebase-issues#37] opened 2024-01-24 20:09 UTC
## MS official site, Press and other 3rd party links
* support.mozilla.com [Outlook and other apps are unable to connect to Outlook.com](https://support.microsoft.com/en-us/office/outlook-and-other-apps-are-unable-to-connect-to-outlook-com-f4202ebf-89c6-4a8a-bec3-3d60cf7deaef)
* [How To Geek: Thunderbird Has a Problem With Outlook, Hotmail, and Live Email Addresses - The problem stems from changes to Microsoft's authentication systems.](https://www.howtogeek.com/thunderbird-has-a-problem-with-outlook-hotmail-and-live-email-addresses/)

## Description of the problem and solutions

* See also question [SUMO Question 1437606: Thunderbird conflict with Hotmail](https://support.mozilla.org/en-US/questions/1437606)
* In this KB article (https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202) there is no clear description of how to switch the password method from `Normal password` to `OAuth2` in Thunderbird. There is a screencap is this SUMO article of someone who successfully did this, also copied below, (https://support.mozilla.org/en-US/questions/1417298#answer-1588949) which it would likely be helpful to replicate. I think this, along with an updated date of January 2024, would help users with this issue. 
![2023-07-05-16-02-16-e0a70f](https://github.com/thunderbird/knowledgebase-issues/assets/152316395/09e19e01-bbaa-4d79-9362-18138654c79e)

- [x] On the Hotmail/Outlook side: 2 step verification must be on. See MS KB Article: [How to use two-step verification with your Microsoft account](https://support.microsoft.com/en-us/account-billing/how-to-use-two-step-verification-with-your-microsoft-account-c7910146-672f-01e9-50a0-93b4585e7eb4)
- [x] Cookies must be set to ON in Thunderbird <del>default browser e.g. Firefox or Chrome</del>
- [x] On the TB side: Thunderbird account settings for the outlook.com/hotmail account IMAP must be set to `OAuth2` AND not `Password`
- [x] <del>On the TB side: you may have to change SMTP to `OAuth2` and use an application specific password as well: See Microsoft KB article: https://support.microsoft.com/en-us/account-billing/using-app-passwords-with-apps-that-don-t-support-two-step-verification-5896ed9b-4263-e681-128a-a6f2979a7944 </del><-- update looks like all you have to do is change it to `OAuth2` for both SMTP and IMAP
- [x] add screenshots
- [x] add an SMTP screenshot
- [x] add a note re: hat due to MS's "diversity" :-) of servers and deployments that there is no definitive solution/workaround and that TB could be broken again by MS at any time at any server in the field due to A/B testing and other stuff
- [x] add TOC
- [x] fix formatting to make it simpler

**Comment by rtanglao** [comment] 2024-01-26 22:07
WIP: https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275237

**Comment by rtanglao** [comment] 2024-01-30 02:08
* as suggested by @plwt , changing to "As of January 2024". Thanks Paul! <-- done in https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275438

**Comment by rtanglao** [comment] 2024-01-30 05:28
* added screenshots: see https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275440

**Comment by rtanglao** [comment] 2024-01-30 22:33
* The howtogeek story is not 100% correct **at least in my experience.** You don't need an App password. i tested it as follows

1. In the web interface at outlook.com i created a new hotmail account, let's call it newhm@hotmail.com
2. i added newhm@hotmail.com
3. I set 2FA on with an email account (my gmail account as the second factor)
4. i added newhm@hotmail.com to TB
5. i couldn't send or receive email with newhm
6. i changed IMAP and SMTP to `OAuth2` (TB autoconfig set it to `Normal Password`
7. i tried to send and receive email with newhm and it worked (in the process firefox opened to the MS site and prompted me for the password, i entered my newhm password and also the 2FA code from gmail)

hooray for microsoft lack of clarity :-)
(i tested on Windows 11, Ubuntu and macOS all with the same results)

* Re: `Mozilla is working to resolve the problem. Presumably, Thunderbird needs a new OAuth setup with advanced MFA support. In the meantime, Thunderbird users must go down a circuitous route to receive emails from their Outlook, Hotmail, and Live inboxes. The steps are outlined in a [Mozilla support post](https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202) and in several [Reddit threads](https://www.reddit.com/r/Thunderbird/comments/19fevs6/finally_found_the_fix_for_this_msft_email_issue/), but we'll give you the gist of it here.` <-- I respectfullly disagree. I don't think we need to fix anything in Thunderbird nor do users need to generate an App Password but I could be wrong.
* Re: `Unfortunately, this story is accompanied by an additional problem. Several email clients, including Thunderbird and the official Outlook app, cannot maintain a connection with Microsoft's email services. Logging in with an App Password works, but the account randomly disconnects. Microsoft is [investigating](https://support.microsoft.com/en-us/office/outlook-and-other-apps-are-unable-to-connect-to-outlook-com-f4202ebf-89c6-4a8a-bec3-3d60cf7deaef) the issue and explicitly mentions Thunderbird in its support post.` <-- I cannot reproduce this. Logging in with the outlook.com password, i.e. not the App Password works and I have had no issues with random disconnects in Thunderbird in my testing

**Comment by monica-thunderbird** [comment] 2024-01-31 19:08
Would it also help to add that users may need to enable cookies in Thunderbird settings to be sure that these changes persist, since there is a strong non-zero probability that a fair number of users do not have cookies enabled? a graphic to show the setting enabled might be helpful as well.

**Comment by rtanglao** [comment] 2024-01-31 23:49
> Would it also help to add that users may need to enable cookies in Thunderbird settings to be sure that these changes persist, since there is a strong non-zero probability that a fair number of users do not have cookies enabled? a graphic to show the setting enabled might be helpful as well.
I added this to the checklist in comment 0: `Cookies must be set to ON in default browser e.g. Firefox or Chrome`. Please let me know if I am missing any nuances here @monica-thunderbird !

**Comment by rtanglao** [comment] 2024-02-01 01:59
The following were fixed in [revision 275525](https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275525)
* On the Hotmail/Outlook side: 2 step verification must be on. See MS KB Article: [How to use two-step verification with your Microsoft account](https://support.microsoft.com/en-us/account-billing/how-to-use-two-step-verification-with-your-microsoft-account-c7910146-672f-01e9-50a0-93b4585e7eb4)
* Cookies must be set to ON in default browser e.g. Firefox or Chrome
* add an SMTP screenshot
* add a note re: hat due to MS's "diversity" :-) of servers and deployments that there is no definitive solution/workaround and that TB could be broken again by MS at any time at any server in the field due to A/B testing and other stuff
* add TOC
* fix formatting to make it simpler

**Comment by rtanglao** [comment] 2024-02-01 02:02
* @wsmwk @dannycolin could you or any other veteran contributor please proofread https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275525 if good to go, set it to `Ready for Localization`. If not please create another revision or leave a comment here or on Matrix.

**Comment by rtanglao** [comment] 2024-02-01 17:57
* Changed `{note}` to `{warning}` and fixed some typos https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275603

**Comment by rtanglao** [comment] 2024-02-01 20:02
* Had it wrong, cookies have to be on in Thunderbird NOT the default browser. Fixed in https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275611

**Comment by rtanglao** [comment] 2024-02-05 17:10
* @Mozinet-fr added a revision [275730](https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202/revision/275730) so closing! Thanks M!

**Comment by rtanglao** [comment] 2024-02-05 17:12
@christ1 also helped! thanks, closing for real this time!

**Closed by rtanglao** 2024-02-05 17:12 UTC
Labels: microsoft, msoauth, outlook.com, hotmail.com
